/**
 * NEON / POSTGRESQL SEED GENERATOR
 * ------------------------------------------------------------------
 * Emits db/seed.sql from the SAME seed modules the application uses,
 * so the database and the running prototype can never drift apart.
 *
 * Usage:  npx tsx scripts/generate-seed-sql.ts
 * Output: db/seed.sql
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SCHOOL_DATA, TEACHING_BLOCKS } from '../src/lib/data/index';
import { getStudentGroup, STUDENT_BY_ID } from '../src/lib/data/students';
import { formatTime } from '../src/lib/time';
import { DAY_PATTERNS } from '../src/lib/data/timetable';
import { toLesson } from '../src/lib/engine/timetable-engine';
import { DAYS } from '../src/lib/types';

const q = (s: string) => `'${String(s).replace(/'/g, "''")}'`;
const lines: string[] = [];

/** Student rows enriched with the teaching group derived at seed time. */
const STUDENT_TABLE = SCHOOL_DATA.students.map((s) => ({
  student_id: s.studentId,
  student_number: s.studentNumber,
  name: s.name,
  year_group: s.yearGroup,
  teaching_group: getStudentGroup(s.studentId),
  face_template_id: s.faceTemplateId,
  backup_pin: s.backupPin,
}));

lines.push('-- ==================================================================');
lines.push('-- SCAS — seed data');
lines.push('-- Generated by scripts/generate-seed-sql.ts from src/lib/data/.');
lines.push('-- Do not edit by hand; re-run the generator instead.');
lines.push('-- ==================================================================');
lines.push('');
lines.push('BEGIN;');
lines.push('');

/* ---------------- reference data ---------------- */
lines.push('-- Students -------------------------------------------------');
for (const s of STUDENT_TABLE) {
  lines.push(
    `INSERT INTO students (student_id, student_number, name, year_group, teaching_group, active, face_template_id, backup_pin) VALUES ` +
      `(${q(s.student_id)}, ${q(s.student_number)}, ${q(s.name)}, ${q(s.year_group)}, ${q(s.teaching_group)}, TRUE, ${q(s.face_template_id)}, ${q(s.backup_pin)});`,
  );
}
lines.push('');

lines.push('-- Teachers -------------------------------------------------');
for (const t of SCHOOL_DATA.teachers) {
  lines.push(
    `INSERT INTO teachers (teacher_id, name) VALUES (${q(t.teacherId)}, ${q(t.name)});`,
  );
}
lines.push('');

lines.push('-- Subjects -------------------------------------------------');
for (const s of SCHOOL_DATA.subjects) {
  lines.push(
    `INSERT INTO subjects (subject_id, name, abbreviation) VALUES (${q(s.subjectId)}, ${q(s.name)}, ${q(s.abbreviation)});`,
  );
}
lines.push('');

lines.push('-- Rooms ----------------------------------------------------');
for (const r of SCHOOL_DATA.rooms) {
  lines.push(`INSERT INTO rooms (room_id, room_name) VALUES (${q(r.roomId)}, ${q(r.roomName)});`);
}
lines.push('');

lines.push('-- Classes --------------------------------------------------');
for (const c of SCHOOL_DATA.classes) {
  lines.push(
    `INSERT INTO classes (class_id, subject_id, teacher_id, "group") VALUES (${q(c.classId)}, ${q(c.subjectId)}, ${q(c.teacherId)}, ${q(c.group)});`,
  );
}
lines.push('');

/* ---------------- enrolments (batched) ---------------- */
lines.push('-- Enrolments (student x class x week) -------------------------');
{
  const values: string[] = [];
  for (const e of SCHOOL_DATA.enrolments) {
    values.push(`(${q(e.studentId)}, ${q(e.classId)}, ${q(e.week)})`);
  }
  for (let i = 0; i < values.length; i += 200) {
    lines.push(
      `INSERT INTO student_enrolments (student_id, class_id, week) VALUES ${values.slice(i, i + 200).join(', ')};`,
    );
  }
}
lines.push('');

/* ---------------- timetable blocks (batched) ---------------- */
lines.push('-- Timetable blocks -------------------------------------------');
{
  const values: string[] = SCHOOL_DATA.timetableBlocks.map(
    (b) =>
      `(${q(b.blockId)}, ${q(b.week)}, ${q(b.day)}, ${b.startTime}, ${b.endTime}, ${q(b.classId)}, ${q(b.roomId)})`,
  );
  for (let i = 0; i < values.length; i += 150) {
    lines.push(
      `INSERT INTO timetable_blocks (block_id, week, day, start_time, end_time, class_id, room_id) VALUES ${values.slice(i, i + 150).join(', ')};`,
    );
  }
}
lines.push('');

/* ---------------- terminals ---------------- */
lines.push('-- Terminals -------------------------------------------------');
for (const r of SCHOOL_DATA.rooms) {
  if (r.roomId === 'B101' || r.roomId === 'B102' || r.roomId === 'B103') continue;
  lines.push(
    `INSERT INTO terminals (terminal_id, room_id, label, status, mode, queued_scans) VALUES ` +
      `(${q('T-' + r.roomId)}, ${q(r.roomId)}, ${q('SCAS Terminal ' + r.roomName)}, 'ONLINE', 'NORMAL', 0);`,
  );
}
lines.push('');
lines.push('COMMIT;');
lines.push('');

/* ---------------- summary ---------------- */
const groupCounts: Record<string, number> = {};
for (const s of STUDENT_TABLE) groupCounts[s.teaching_group] = (groupCounts[s.teaching_group] ?? 0) + 1;

lines.push('-- ============================================================');
lines.push(`-- Students:      ${STUDENT_TABLE.length}`);
lines.push(`-- Teachers:      ${SCHOOL_DATA.teachers.length}`);
lines.push(`-- Subjects:      ${SCHOOL_DATA.subjects.length}`);
lines.push(`-- Rooms:         ${SCHOOL_DATA.rooms.length}`);
lines.push(`-- Classes:       ${SCHOOL_DATA.classes.length}`);
lines.push(`-- Enrolments:    ${SCHOOL_DATA.enrolments.length}`);
lines.push(`-- Blocks:        ${SCHOOL_DATA.timetableBlocks.length} (${TEACHING_BLOCKS.length} teaching)`);
Object.entries(groupCounts).forEach(([g, n]) => lines.push(`--   group ${g}:   ${n} students`));
lines.push('-- ============================================================');

writeFileSync(resolve(process.cwd(), 'db/seed.sql'), lines.join('\n'), 'utf8');
console.log(`db/seed.sql written — ${lines.length} lines`);
console.log(`  students    ${STUDENT_TABLE.length}`);
console.log(`  classes     ${SCHOOL_DATA.classes.length}`);
console.log(`  enrolments  ${SCHOOL_DATA.enrolments.length}`);
console.log(`  blocks      ${SCHOOL_DATA.timetableBlocks.length}`);
